spring.application.name=EmergencyLocator

#=======================
#DTABASE CONFIGURATION
#=======================
spring.datasource.url=jdbc:postgresql://localhost:5432/emergencyLocator
spring.datasource.username:postgres
spring.datasource.password:root@123
spring.datasource.driver-class-name=org.postgresql.Driver

#=========================
# JPA/HIBERNATE
#=========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.porperties.hibernate.format_sql=true

# PostgreSQL   dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#=========================
# SERVER PORT
#=========================
server.port=8080

#jwtsecratekey
jwt.secrateKey=asff5saf5saaggrsfgssd5g8ra1aa6grgaht1sh8tha1a6a